### ISSUE TITLE
BlackJack.md 작성

### ISSUE THREAD

**Issue by yujamint** [mbsc-zzang/Black_Jack#1]
## 당신이 해야할 일
블랙잭 게임의 규칙 등 정보 조사 후에 BlackJack.md 작성

## 해야할 일
- [x] 블랙잭 게임 규칙 조사
- [x] 블랙잭 게임 역사 조사
- [x] BlackJack.md 작성

**Comment by zoomin99** [comment]
흠 좋습니다 진행하시죠
